#!/usr/bin/env bash
set -euo pipefail

SESSION="${SESSION:-gaze_wam_open_8gpu}"
ROOT="${ROOT:-/mnt/workspace/shenyibo/gaze-wam}"

cd "$ROOT"

if tmux has-session -t "$SESSION" 2>/dev/null; then
  echo "tmux session already exists: $SESSION" >&2
  tmux ls
  exit 1
fi

if [[ ! -f ".venv/bin/activate" ]]; then
  echo "Missing project venv at $ROOT/.venv" >&2
  exit 1
fi

if [[ ! -d "data/hot3d_open.zarr" ]]; then
  echo "Missing dataset at $ROOT/data/hot3d_open.zarr" >&2
  exit 1
fi

mkdir -p data/outputs

RUN_ID="$(date +%Y%m%d_%H%M%S)"
OUTPUT_DIR="${OUTPUT_DIR:-data/outputs/hot3d_open_cosmos_intensity_softplus_latent_8gpu_amp_${RUN_ID}}"
CONFIG_NAME="${CONFIG_NAME:-train_gaze_wam_open_only_cosmos_workspace}"
HEATMAP_OBJECTIVE="${HEATMAP_OBJECTIVE:-}"
NUM_EPOCHS="${NUM_EPOCHS:-200}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-0}"
MAX_VAL_STEPS="${MAX_VAL_STEPS:-20}"
BATCH_SIZE="${BATCH_SIZE:-16}"
GRADIENT_ACCUMULATE_EVERY="${GRADIENT_ACCUMULATE_EVERY:-4}"
PRETRAINED="${PRETRAINED:-true}"
LOGGING_MODE="${LOGGING_MODE:-disabled}"
RESUME="${RESUME:-false}"
RESUME_EPOCH="${RESUME_EPOCH:-}"
CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-1}"
SAMPLE_EVERY="${SAMPLE_EVERY:-1}"
HEATMAP_DIM="${HEATMAP_DIM:-16}"
HEATMAP_SPATIAL_DECODER="${HEATMAP_SPATIAL_DECODER:-cosmos_tokenizer}"
HEATMAP_COSMOS_ENCODER_PATH="${HEATMAP_COSMOS_ENCODER_PATH:-data/checkpoints/cosmos_tokenizer/Cosmos-Tokenizer-CI16x16/encoder.jit}"
HEATMAP_COSMOS_DECODER_PATH="${HEATMAP_COSMOS_DECODER_PATH:-data/checkpoints/cosmos_tokenizer/Cosmos-Tokenizer-CI16x16/decoder.jit}"
HEATMAP_COSMOS_INPUT_RANGE="${HEATMAP_COSMOS_INPUT_RANGE:-minus_one_one}"
HEATMAP_COSMOS_OUTPUT_RANGE="${HEATMAP_COSMOS_OUTPUT_RANGE:-minus_one_one}"
HEATMAP_COSMOS_INPUT_NORMALIZATION="${HEATMAP_COSMOS_INPUT_NORMALIZATION:-max}"
HEATMAP_LATENT_SCALE="${HEATMAP_LATENT_SCALE:-0.25}"
HEATMAP_LATENT_OFFSET="${HEATMAP_LATENT_OFFSET:-0.0}"
HEATMAP_LATENT_STATS_PATH="${HEATMAP_LATENT_STATS_PATH:-data/outputs/cosmos_heatmap_latent_stats/hot3d_open_ci16x16_random4096_seed42.json}"
HEATMAP_SCHEDULER_CLIP_SAMPLE="${HEATMAP_SCHEDULER_CLIP_SAMPLE:-true}"
HEATMAP_DISTRIBUTION_MODE="${HEATMAP_DISTRIBUTION_MODE:-intensity_softplus}"
HEATMAP_DSNT_TEMPERATURE="${HEATMAP_DSNT_TEMPERATURE:-0.1}"
HEATMAP_DIFFUSION_FINAL_LOSS_ENABLED="${HEATMAP_DIFFUSION_FINAL_LOSS_ENABLED:-}"
HEATMAP_FINAL_LOSS_TIMESTEP_WEIGHTING="${HEATMAP_FINAL_LOSS_TIMESTEP_WEIGHTING:-}"
HEATMAP_XY_LOSS_WEIGHT="${HEATMAP_XY_LOSS_WEIGHT:-}"
HEATMAP_POINT_NLL_LOSS_WEIGHT="${HEATMAP_POINT_NLL_LOSS_WEIGHT:-}"
HEATMAP_JS_LOSS_WEIGHT="${HEATMAP_JS_LOSS_WEIGHT:-}"

CMD=$(cat <<EOF
cd "$ROOT" && \
source .venv/bin/activate && \
mkdir -p "$OUTPUT_DIR" && \
OUTPUT_DIR="$OUTPUT_DIR" \
CONFIG_NAME="$CONFIG_NAME" \
HEATMAP_OBJECTIVE="$HEATMAP_OBJECTIVE" \
NUM_EPOCHS="$NUM_EPOCHS" \
MAX_TRAIN_STEPS="$MAX_TRAIN_STEPS" \
MAX_VAL_STEPS="$MAX_VAL_STEPS" \
BATCH_SIZE="$BATCH_SIZE" \
GRADIENT_ACCUMULATE_EVERY="$GRADIENT_ACCUMULATE_EVERY" \
PRETRAINED="$PRETRAINED" \
LOGGING_MODE="$LOGGING_MODE" \
RESUME="$RESUME" \
RESUME_EPOCH="$RESUME_EPOCH" \
CHECKPOINT_EVERY="$CHECKPOINT_EVERY" \
SAMPLE_EVERY="$SAMPLE_EVERY" \
HEATMAP_DIM="$HEATMAP_DIM" \
HEATMAP_SPATIAL_DECODER="$HEATMAP_SPATIAL_DECODER" \
HEATMAP_COSMOS_ENCODER_PATH="$HEATMAP_COSMOS_ENCODER_PATH" \
HEATMAP_COSMOS_DECODER_PATH="$HEATMAP_COSMOS_DECODER_PATH" \
HEATMAP_COSMOS_INPUT_RANGE="$HEATMAP_COSMOS_INPUT_RANGE" \
HEATMAP_COSMOS_OUTPUT_RANGE="$HEATMAP_COSMOS_OUTPUT_RANGE" \
HEATMAP_COSMOS_INPUT_NORMALIZATION="$HEATMAP_COSMOS_INPUT_NORMALIZATION" \
HEATMAP_LATENT_SCALE="$HEATMAP_LATENT_SCALE" \
HEATMAP_LATENT_OFFSET="$HEATMAP_LATENT_OFFSET" \
HEATMAP_LATENT_STATS_PATH="$HEATMAP_LATENT_STATS_PATH" \
HEATMAP_SCHEDULER_CLIP_SAMPLE="$HEATMAP_SCHEDULER_CLIP_SAMPLE" \
HEATMAP_DISTRIBUTION_MODE="$HEATMAP_DISTRIBUTION_MODE" \
HEATMAP_DSNT_TEMPERATURE="$HEATMAP_DSNT_TEMPERATURE" \
HEATMAP_DIFFUSION_FINAL_LOSS_ENABLED="$HEATMAP_DIFFUSION_FINAL_LOSS_ENABLED" \
HEATMAP_FINAL_LOSS_TIMESTEP_WEIGHTING="$HEATMAP_FINAL_LOSS_TIMESTEP_WEIGHTING" \
HEATMAP_XY_LOSS_WEIGHT="$HEATMAP_XY_LOSS_WEIGHT" \
HEATMAP_POINT_NLL_LOSS_WEIGHT="$HEATMAP_POINT_NLL_LOSS_WEIGHT" \
HEATMAP_JS_LOSS_WEIGHT="$HEATMAP_JS_LOSS_WEIGHT" \
bash train_scripts/train_gaze_wam_open_only_8gpu_amp.sh 2>&1 | tee -a "$OUTPUT_DIR/console.log"
EOF
)

tmux new-session -d -s "$SESSION" "$CMD"
echo "started tmux session: $SESSION"
echo "attach: tmux attach -t $SESSION"
echo "output_dir: $ROOT/$OUTPUT_DIR"
